AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Style/GlobalVars:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/*

Style/StringLiterals:
  Exclude:
    - spec/*

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false
