AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 25

Style/GlobalVars:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  Exclude:
    - "spec/**/*"

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 8
