name: Pull request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ["2.7.3", "3.1.3"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version: ${{ matrix.ruby }} # Not needed with a .ruby-version file
          bundler-cache: true

      - name: Install Dependencies
        run: |
          echo "Installing Bundler..."
          gem install bundler

      - name: Install Gems
        run: |
          echo "Installing gems..."
          bundle install

      - name: Run Tests
        run: |
          echo "🧪 Testing..."
          bundle exec rspec

      - name: Run Rubocop
        run: |
          echo "🧪 Robocop..."
          bundle exec rubocop

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: get_version
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          export VERSION=$(cat version.txt)-$COMMIT_SHA
          echo "Version: $VERSION"
          echo "version=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pamitedu/toy-robot:${{ steps.get_version.outputs.version }}

      - name: Build and push
        id: docker_build2
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: pamitedu/toy-robot:${{ steps.get_version.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
