name: Pull request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7.3', '3.1.3']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version: ${{ matrix.ruby }} # Not needed with a .ruby-version file
          bundler-cache: true

      - name: Install Dependencies
        run: |
          echo "Installing Bundler..."
          gem install bundler

      - name: Install Gems
        run: |
          echo "Installing gems..."
          bundle install

      - name: Run Tests
        run: |
          echo "🧪 Testing..."
          bundle exec rspec

      - name: Run Rubocop
        run: |
          echo "🧪 Robocop..."
          bundle exec rubocop
